### ISSUE TITLE
Adapt-devtools's  Open Course Map breaks rub develop

### ISSUE THREAD

**Issue by samumist** [oliverfoster/adapt-buildkit-rub#34]
rub develop breaks with the following error message when clicking the `open course
map` button on the [adapt-devtools](https://github.com/cgkineo/adapt-devtools).

No such problem with `grunt` or `rub`.

``` shell
Version v0.1.15
/Volumes/Data/playground/adapt/demo/buildkit/plugins/buildkit-plugin-server/js/index.js:103
                var mimeType = this._mimeTypesByExtension[path.extname(req.stat.filename).split(".")[1]];
                                                                               ^

TypeError: Cannot read property 'filename' of undefined
    at Plugin.next (/Volumes/Data/playground/adapt/demo/buildkit/plugins/buildkit-plugin-server/js/index.js:103:66)
    at /Volumes/Data/playground/adapt/demo/buildkit/plugins/buildkit-plugin-server/js/index.js:125:60
    at SendStream.error (/Volumes/Data/playground/adapt/demo/buildkit/node_modules/serve-static/index.js:117:9)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (/Volumes/Data/playground/adapt/demo/buildkit/node_modules/serve-static/node_modules/send/index.js:275:17)
    at SendStream.headersAlreadySent (/Volumes/Data/playground/adapt/demo/buildkit/node_modules/serve-static/node_modules/send/index.js:363:8)
    at SendStream.send (/Volumes/Data/playground/adapt/demo/buildkit/node_modules/serve-static/node_modules/send/index.js:572:10)
    at onstat (/Volumes/Data/playground/adapt/demo/buildkit/node_modules/serve-static/node_modules/send/index.js:677:10)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by oliverfoster** [comment]
can you try again? have fixed

**Comment by samumist** [comment]
Thanks!
 Yes, it is fixed.
